name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    # Assuming the pom.xml is located in the root directory, remove the -f flag
    # If it's in a subdirectory, adjust the path accordingly
    - name: Run Unit Tests
      run: mvn -B -f tictactoe/pom.xml test

    # Optional: Uploads the test results for visibility
    - name: Archive Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/
